import Head from 'next/head'
import Image from 'next/image'
import Classes from '../components/Classes'
import Header from '../components/header'
import HeroSection from '../components/hero'
import RowSection from '../components/rowSection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cuiabá Cebrac</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <HeroSection />
        <RowSection />
        <Classes />
      </main>

      <footer>
      </footer>
    </div>
  )
}
