import Head from 'next/head'

import Header from '../components/header'
import HeroSection from '../components/heroSection'
import RowSection from '../components/rowSection'
import ClassesSection from '../components/classesSection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cuiabá Cebrac</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <HeroSection />
        <RowSection />
        <ClassesSection />
      </main>

      <footer>
      </footer>
    </div>
  )
}
