import Head from 'next/head'

import Header from '../components/header'
import FooterSection from '../components/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Obrigado! | Cuiabá Cebrac</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <h1>Obrigado!</h1>
      </main>

      <FooterSection />
    </div>
  )
}
